import { Inter } from 'next/font/google';
import StyledComponentsRegistry from '../lib/registry';
import GlobalStyles from '@/styles/GlobalStyles';
import LeftNavbar from '@/components/LeftNavbar';
import Trending from '@/components/Trending';
import { MainWrapper } from './styles';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <GlobalStyles />

          <LeftNavbar />

          <MainWrapper>
            {children}
            <Trending />
          </MainWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
